<<<<<<< HEAD
theme: jekyll-theme-minimal
title:  [Sofie] - DAA 2022
description: My GitHub Page
show_downloads: false
=======
theme: jekyll-theme-minimal
>>>>>>> 02dc99191c200636b13680a0ae53e6136e47e246
